### ISSUE TITLE
得到的二进制文件格式

### ISSUE THREAD

**Issue by Zth9730** [ziyu123/kaldi_feature#1]
您好，我使用compute-fbank-vad 后存储二进制文件为ark文件，
但使用kaldi_io.read_mat读这个ark文件时报错，请问是什么情况？

**Comment by ziyu123** [comment]
> 您好，我使用compute-fbank-vad 后存储二进制文件为ark文件，
> 但使用kaldi_io.read_mat读这个ark文件时报错，请问是什么情况？

提取特征后写的是二进制，把特征以float形式直接写进去的，如果要读的话，只能一个float一个float读

**Comment by Zth9730** [comment]
十分感谢🙏


| |
我
|
|
邮箱：15600919271@163.com
|

签名由 网易邮箱大师 定制

在2020年04月29日 16:40，ziyu 写道：

您好，我使用compute-fbank-vad 后存储二进制文件为ark文件，
但使用kaldi_io.read_mat读这个ark文件时报错，请问是什么情况？

提取特征后写的是二进制，把特征以float形式直接写进去的，如果要读的话，只能一个float一个float读
