### ISSUE TITLE
依赖库问题

### ISSUE THREAD

**Issue by yml-bit** [ziyu123/kaldi_feature#2]
你好，请问有没有小些的数学库供选择呢(或者VS中通用的数学库对应替换)，我想将kaldi特征提取部分单独领出来使用（任意平台，比如window，DSP），但是对kaldi的相互调用有些生疏，大佬可否加你个联系方式沟通学习一下呢

**Comment by 18487083963** [comment]
大佬，我Q1520890081,打扰了

**Comment by ziyu123** [comment]
小点用OpenBLAS吧，VS没有调试过，不过数学库都是通用的，DSP上需要用的话，平台应该由很多限制吧，建议重新写一遍

**Comment by yml-bit** [comment]
多谢！------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;ziyu&quot;<notifications@github.com&gt;
发送时间:&nbsp;2021年2月16日(星期二) 晚上6:02
收件人:&nbsp;&quot;ziyu123/kaldi_feature&quot;<kaldi_feature@noreply.github.com&gt;;
抄送:&nbsp;&quot;High non-speech duty cycle speech enhancement&quot;<1520890081@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ziyu123/kaldi_feature] 依赖库问题 (#2)
